### PR TITLE
New library format + updating tests and paths in examples

### PR DESCRIPTION
**Pull request by h-bode**
@Webbah please confirm :-) 

Tests run, examples run, onliest thing to do is to create a linux fmu for the NetworkSingleInverter.

The good thing is that we can keep all the names of the parameters the same, although the names of the blocks needed to be modified to follow the modelica standards. So we shouldn´t have any problems by using this format

### CODE REVIEW

**Comment by h-bode** [comment]
Updated the documentation directly in the this branch. Hopefully nothing brakes, never did it before like this *prayersmiley*

**Review by Webbah — CHANGES_REQUESTED** [review]
create_fmu.mos does not work on linux:

$ omc create_fmu.mos        
false                                                                                                                            
"[/var/lib/jenkins1/ws/LINUX_BUILDS/tmp.build/openmodelica-1.16.0~dev-627-ge2dd3e1/OMCompiler/Compiler/FrontEnd/ClassLoader.mo:373:13-373:88:writable] Error: Interner Fehler Expected file /home/webbah/Dokumente/GIT/openmodelica-microgrid-gym/OpenModelica_Microgrids/ActiveLoads.mo to exist                                                                                                      
Error: Failed to load package OpenModelica_Microgrids () using MODELICAPATH /home/webbah/Dokumente/GIT/openmodelica-microgrid-gym.
"                                                                                                                                
true                                                                                                                             
""                                                                                                                               
true                                                                                                                             
""                                                                                                                               
true                                                                                                                             
""                                                                                                                               
true                                                                                                                             
""                                                                                                                               
""                                                                                                                               
"Error: Failed to load package OpenModelica_Microgrids (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/webbah/.openmodelica/libraries/.
Error: Klasse OpenModelica_Microgrids.Grids.NetworkSingleInverter konnte nicht im Geltungsbereich von <top> gefunden werden.     
Error: Klasse OpenModelica_Microgrids.Grids.NetworkSingleInverter konnte nicht im Geltungsbereich von <TOP> gefunden werden.     
"

**Comment by h-bode** [comment]
thanks for testing @Webbah .
Works fine on windows, might be an issue with the data path on linux.

I´ll check tomorrow on the linux VM.

**Comment by h-bode** [comment]
Updated two files, should work now on every platform :-)

@Webbah , please update your branch and confirm :-)

**Review by Webbah — APPROVED** [review]

**Pull request merged**
